apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: errorlab
  title: ErrorLab
  description: API de Pokémon con errores controlados para testing de análisis de logs con IA
  annotations:
    backstage.io/kubernetes-id: errorlab
    backstage.io/kubernetes-namespace: errorlab-sandbox
    backstage.io/kubernetes-label-selector: 'app=errorlab'
    prometheus.io/rule: 'pdoc_ai_analyses_total|result'
spec:
  type: service
  lifecycle: experimental
  owner: guests
